spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbrecord?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: wsad8246
    driver-class-name: com.mysql.jdbc.Driver
  security:

#     user:
#       name: user
#       password: useruser

server:
  port: 8081
mybatis:
  config-location: classpath:mybatis-config.xml